export default [
    {
        id: 1,
        title: "Denver Yogis Retreat",
        description: "The program is a balance of unstructured time for deep rest, relaxation, and reflection complemented by optional classes in contemplative practice (yoga, meditation, conscious movement), nature immersion, ecstatic dance, inward reflection periods, and optional individual and group counseling.",
        price: 420,
        coverImg: "yoga.jpg",
        stats: {
            rating: 4.5,
            reviewCount: 7,
        },
        location: "Denver, Colorado",
        openSpots: 0,
    },
    {
        id: 2,
        title: "You Hit Like a Bit@# Boxing Studio",
        description: "All classes will include a variety of bag work, shadow boxing, and footwork. Students will also go through a variety of core, cardio, and strength exercises. Each class will be designed to teach professional boxing and self defense skills. You will gain strength, hand-eye coordination, endurance, and confidence in a full body workout.",
        price: 89,
        coverImg: "boxing.jpg",
        stats: {
            rating: 3.5,
            reviewCount: 3,
        },
        location: "Dallas, Texas",
        openSpots: 0,
    },
    {
        id: 3,
        title: "Diving with Oceanic Travel Co.",
        description: "Explore beaches, reefs, and the open ocean in these diving adventure classes.",
        price: 349,
        coverImg: "swimming.jpg",
        stats: {
            rating: 4.0,
            reviewCount: 3,
        },
        location: "Madeira Islands, Portugal",
        openSpots: 5,
    },
    {
        id: 4,
        title: "Horseback Riding at Lucky Ranch",
        description: "Built on 30+ years of teaching experience, our lesson program provides a solid foundation to reach your riding goals. We offer horseback riding lessons year round to adults and children of all skill levels as well as holiday and Summer camps.",
        price: 79,
        coverImg: "horsebackRiding.jpg",
        stats: {
            rating: 5,
            reviewCount: 10,
        },
        location: "Tyler, Texas",
        openSpots: 8,
    },
    {
        id: 5,
        title: "Hiking Trip Along Great Smoky Mountains",
        description: "The fog-ringed peaks of the Smoky Mountains, which sprawl across the North Carolina–Tennessee border, delight year-round. Come spring, hikers head to Great Smoky Mountains National Park, where they can trek a section of the Appalachian Trail, pausing to catch their breath in meadows bursting with wildflowers. Summer paints the mountains green and lush, while fall stipples them gold and orange as the leaves change. In winter, the Smokies are a wonderland ripe for skiing and all things snow: snowshoeing, snow angels, snowball fights.",
        price: 125,
        coverImg: "hiking.jpg",
        stats: {
            rating: 5,
            reviewCount: 13,
        },
        location: "Great Smoky Mountains, USA",
        openSpots: 11,
    },
    {
        id: 6,
        title: "Moon Walk at the Space Museum",
        description: "The newly upgraded planetarium now features Digistar 6, the world’s leading digital planetarium software and projection system. The Digistar 6 system enables our visitors to fly through the universe, experience the vastness of space, roam planetary surfaces, navigate asteroid fields, and watch the latest fulldome shows. Along with our ability to create unique experiences for the planetarium, we have access to a global cloud library of content and shows we can present. The Digistar Cloud library allows us to keep presentations filled with the latest discoveries. You’ll discover something new every time you visit!",
        price: 69,
        coverImg: "moonTrip.jpg",
        stats: {
            rating: 4,
            reviewCount: 55,
        },
        location: "Seattle, Washington",
        openSpots: 0,
    },
    {
        id: 7,
        title: "Splatter Paint",
        description: "Come and enjoy a private room – AKA our exclusive Splatter Room for two! Experience the fun of splatter painting as you create a piece of art on a canvas or even splatter paint on each other!",
        price: 65,
        coverImg: "splatterPaint.jpg",
        stats: {
            rating: 4.5,
            reviewCount: 66,
        },
        location: "Plano, Texas",
        openSpots: 14,
    },
    {
        id: 8,
        title: "The Dallas World Aquarium",
        description: "An old warehouse at 1801 North Griffin Street, near the Historic West End District in downtown Dallas, became the original site of The Dallas World Aquarium, opening to the public in October 1992.",
        price: 55,
        coverImg: "aquarium.jpg",
        stats: {
            rating: 4,
            reviewCount: 24,
        },
        location: "Dallas, Texas",
        openSpots: 14,
    },
    {
        id: 9,
        title: "Go Ape Treetop Zipline Adventure",
        description: "This is the big one! Our original Treetop Adventure in the canopy. Looking for 28 foot high tree-to-tree crossings, super long ziplines and heart-stopping Tarzan swings? Search no more. A 2-3 hour adventure like no other awaits you.",
        price: 123,
        coverImg: "zipline.jpg",
        stats: {
            rating: 4.5,
            reviewCount: 4,
        },
        location: "Plano, Texas",
        openSpots: 10,
    },
    {
        id: 10,
        title: "Labrynth",
        description: "Labyrinth is the perfect place to celebrate any occasion. You and your friends and family will have the time of your life as you navigate the experiences within the labyrinth. Your party goers will find a new challenge in every room. You bring the people and we’ll provide the memories.",
        price: 50,
        coverImg: "labrynth.jpg",
        stats: {
            rating: 3.5,
            reviewCount: 6,
        },
        location: "Online",
        openSpots: 18,
    },
]